apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
  labels:
    app: hma
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hma
    
  template:
    metadata:
      labels:
        app: hma
    spec:
      containers:
        - name: hma-container
          image: sadanchandra99/hotel-management-app:1.0
          
          env:
            - name: MYSQL_ROOT_HOST
              valueFrom:
                configMapKeyRef:
                  name: mysql-configmap
                  key: host
            
            
            - name: MYSQL_USER
              valueFrom:
                configMapKeyRef:
                  name: mysql-configmap
                  key: username
            
            - name: MYSQL_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: mysql-configmap
                  key: password

            - name: MYSQL_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: mysql-configmap
                  key: name
          ports:
          - containerPort: 8318


---


apiVersion: v1 
kind: Service 
metadata: 
  name: hma
  labels: 
    name: hma
spec:
  selector: 
    app: hma
  ports:
    - protocol: TCP
      port: 8318
      targetPort: 8318
      nodePort: 31999
  type: NodePort