apiVersion: apps/v1
kind: Deployment # Create a deployment
metadata:
  name: mysql-deployment # Set the name of the deployment
  labels:
    app: mysql-db
spec:
  replicas: 1 # Set 2 deployment replicas
  selector:
    matchLabels:
      app: mysql-db
  template:
    metadata:
      labels:
        app: mysql-db
    spec:
      containers:
        - name: mysql-container
          image: mysql:5.7 # Docker image
          
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom: 
                configMapKeyRef:
                  name: mysql-configmap  
                  key: password
            - name: MYSQL_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: mysql-configmap
                  key: name
          ports:
            - containerPort: 3306 # Exposing the container port 5432 for PostgreSQL client connections.
              name: mysql-db

         
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
spec:
  selector:
    app: mysql-db
  ports:
     
    - port: 3306
      targetPort: 3306
  clusterIP: None